<?php
// $Id: twocol.inc,v 1.1.2.2 2010/05/21 06:25:15 merlinofchaos Exp $

// Plugin definition
$plugin = array(
  'title' => t('commonpassion.org'),
  'icon' => 'onerowtwocols.png',
 'theme' => 'onerowtwocols',
  'css' => 'onerowtwocols.css',
  'panels' => array(
    'logo' => t('Logo'),
    'logo_right' => t('Logo Right'),
    'top' => t('Top'),
    'category1' => t('Category1'),
    'category2' => t('Category2'),
    'category3' => t('Category3'),
    'welcome' => t('Welcome Message'),
    'group_event' => t('Group Event'),
    'group_members' => t('Group Members'),
    'group_toolbox_menu' => t('Group Toolbox Menu'),
    'group_posts' => t('Group Posts'),
    'left_below' => t('Left below'),
    'right_below' => t('Right below'),
    'bottom_post' => t('Bottom'),
  ),
);



 